### ISSUE TITLE
New feature: align comments 

### ISSUE THREAD

**Issue by gregleleu** [seasmith/AlignAssign#10]
Sometimes it can be usfeul to add comments directly to the right of code, as such:
```
data %>%
  group_by(group_var) %>%  ## Using the grouping var
  mutate(
    var_1 = ...,                     ## The first feature
    var_2 = ...,                      ## The second
)
```

But as far as I know we have to align the "#" manually. I imagine your addin could it quite fast.

**Comment by seasmith** [comment]
The [AlignRegex](https://github.com/seasmith/AlignRegex) package was designed to handle this sort of thing. I haven't tried aligning comment characters but should be totally doable, though I don't know how it would integrate into this package.
