### ISSUE TITLE
Recommended Keyboard Shortcut = ? (Enhancement req.)

### ISSUE THREAD

**Issue by knbknb** [seasmith/AlignAssign#2]
Enhancement request for the documentation:

Which Keyboard Shortcut would you recommend? Is there a common "base combination" or a guideline? Please mention this in the documentation / the README.md file.
Example: *"Custom keyboard shortcuts for addins should be a  CTRL-SHIFT combination"*, or *"addins shoud use one of the F1-F12 keys"*.

If there is no such guideline, then so be it.

**Comment by seasmith** [comment]
Keyboard shortcuts need to be and should be set by the individual user.

I can tell you that I use _Ctrl + Shift + Z_ and _Ctrl + Shift + X_ for the two add-ins from this package - merely for convenience of using the mouse with the right-hand while executing the add-in with left-hand in rapid sequence.
